Project Airplane_Management_System {
  database_type: 'PostgreSQL'
  Note: '''
    # Airplane Management System Database
    
    This is a database schema for an airplane management system application.
    
    ## Tables
    
    - `Airline`: Contains information about airlines.
    - `Airport`: Stores details about airports.
    - `Airplane`: Records details about airplanes operated by airlines.
    - `AirplaneFlight`: Represents flights operated by airplanes.
    - `FlightPassenger`: Stores passenger details for each flight.
    - `AirplaneTicket`: Represents tickets booked by passengers.
    - `AirplaneTicketAddOnType`: Tracks additional services booked along with tickets.
    - `GlobalConfiguration`: Stores global configurations for the system.
    - `AirplaneFlightCrew`: Records crew members assigned to flights.
  '''
}

Table Airline {
  Name varchar [pk, not null]
  FoundingYear int [not null, note: 'Non-negative']
  CustomerCareNumber varchar [not null]
  Headquarters varchar [not null]
}

Table Airport {
  Name varchar [pk, not null]
  Code varchar [not null, unique]
  City varchar
  Country varchar
}

Table Airplane {
  Name varchar [pk, not null]
  AirlineName varchar [not null]
  Model varchar [not null]
  CapacitySeat int [not null]
  Capacityluggage int [not null]
}

Table AirplaneFlight {
  Name varchar [pk, not null]
  AirplaneName varchar [not null]
  DateOfDeparture date [not null]
  TimeOfDeparture time [not null]
  Duration interval [not null]
  SourceAirportName varchar [not null]
  DestinationAirportName varchar [not null]
  GateNumber varchar [not null]
  FlightPrice decimal [not null]
  CapacitySeat int [not null]
  Capacityluggage int [not null]
  Status varchar [default: 'Scheduled']
}

Table AirplaneTicket {
  ID varchar [pk, increment]
  PassengerName array [not null]
  FlightName varchar [not null]
  Seat varchar
  AddOnItem varchar [not null]
  DateOfDeparture date [not null]
  TimeOfDeparture time [not null]
  Duration interval [not null]
  SourceAirportName varchar [not null]
  DestinationAirportName varchar [not null]
  GateNumber varchar
  FlightPrice decimal 
  TotalAmount decimal [not null]
  Status varchar [default: 'Booked']
}

Table AirplaneTicketAddOnType {
  Name varchar [pk, not null]
  Description varchar
}

Table AirplaneTicketAddOnItem {
  AddOnTypeName varchar [not null]
  Amount decimal [default: 0]

}

Ref: Airline.Name > Airplane.AirlineName
Ref: AirplaneFlight.AirplaneName > Airplane.Name
Ref: AirplaneFlight.SourceAirportName > Airport.Name
Ref: AirplaneFlight.DestinationAirportName > Airport.Name
Ref: AirplaneTicket.FlightName > AirplaneFlight.Name
Ref: AirplaneTicketAddOnItem.TicketID > AirplaneTicket.ID
Ref: AirplaneTicketAddOnItem.AddOnTypeName > AirplaneTicketAddOnType.Name
